// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-EUHkAsmiutq0H1TlQ80w0afjcB__doc',
    appId: '1:890974174063:web:e60322c5a0f22a8eed469a',
    messagingSenderId: '890974174063',
    projectId: 'doctorappointmentapp-a562f',
    authDomain: 'doctorappointmentapp-a562f.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-a562f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYkNuOlY3-hQm5jLylGgyyv3nQIFDmBKQ',
    appId: '1:890974174063:android:c551372724adb8f6ed469a',
    messagingSenderId: '890974174063',
    projectId: 'doctorappointmentapp-a562f',
    storageBucket: 'doctorappointmentapp-a562f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirvLP00JYiy3X1ZevsCJ4jJi4wad6Z98',
    appId: '1:890974174063:ios:b0e0eee220d0bd4eed469a',
    messagingSenderId: '890974174063',
    projectId: 'doctorappointmentapp-a562f',
    storageBucket: 'doctorappointmentapp-a562f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirvLP00JYiy3X1ZevsCJ4jJi4wad6Z98',
    appId: '1:890974174063:ios:b0e0eee220d0bd4eed469a',
    messagingSenderId: '890974174063',
    projectId: 'doctorappointmentapp-a562f',
    storageBucket: 'doctorappointmentapp-a562f.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-EUHkAsmiutq0H1TlQ80w0afjcB__doc',
    appId: '1:890974174063:web:b0e21d782217c9b0ed469a',
    messagingSenderId: '890974174063',
    projectId: 'doctorappointmentapp-a562f',
    authDomain: 'doctorappointmentapp-a562f.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-a562f.firebasestorage.app',
  );
}
